// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsIIU3J_PpnbjCuBjkyugTZ49fxB3wpvs',
    appId: '1:705025460700:web:911fd3ef0c82c0d8452719',
    messagingSenderId: '705025460700',
    projectId: 'currensee-e425e',
    authDomain: 'currensee-e425e.firebaseapp.com',
    storageBucket: 'currensee-e425e.appspot.com',
    measurementId: 'G-FQ4GSN8D64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuUJMmmCFEPKidZ9vAXlSbcsECbVgGPw',
    appId: '1:705025460700:android:c9909069a5e046c6452719',
    messagingSenderId: '705025460700',
    projectId: 'currensee-e425e',
    storageBucket: 'currensee-e425e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmb2NfxVdsagVoKIcafBnd9J0t0-L4SuE',
    appId: '1:705025460700:ios:b796b231c1b81ced452719',
    messagingSenderId: '705025460700',
    projectId: 'currensee-e425e',
    storageBucket: 'currensee-e425e.appspot.com',
    iosClientId: '705025460700-3chcus9m45qpovq0827abbcgq2oouhea.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmb2NfxVdsagVoKIcafBnd9J0t0-L4SuE',
    appId: '1:705025460700:ios:b796b231c1b81ced452719',
    messagingSenderId: '705025460700',
    projectId: 'currensee-e425e',
    storageBucket: 'currensee-e425e.appspot.com',
    iosClientId: '705025460700-3chcus9m45qpovq0827abbcgq2oouhea.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsIIU3J_PpnbjCuBjkyugTZ49fxB3wpvs',
    appId: '1:705025460700:web:a91560cb09a09210452719',
    messagingSenderId: '705025460700',
    projectId: 'currensee-e425e',
    authDomain: 'currensee-e425e.firebaseapp.com',
    storageBucket: 'currensee-e425e.appspot.com',
    measurementId: 'G-5X6QFGKPVS',
  );
}
